server.port: 10020
kafka.server.hosts-ports: 192.168.1.221:9092,192.168.1.221:9093

kafka.topic: asdfasdf
topic.groupid: 1
consume.thread.count: 10
serializer.encoding: kafka.serializer.StringEncoder


# logging
logging.level.root: INFO
#logging.level.org.springframework.web=DEBUG
logging.file: /data/logs/news-consume-spider/data-consumer.log

content.key.Regexs: 评论|参与

index.save.url: http://192.168.1.221:9666/newsDoc/save

